name: Deploy on QA

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy_on_qa:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v2
      
      - name: Create customer Env file
        working-directory: ./customer
        run: |
          touch .env
          echo APP_SECRET='MySecretKey' >> .env
          echo MONGODB_URI='mongodb+srv://hiranya:hiranya@cluster0.dn0whwc.mongodb.net/customer?retryWrites=true&w=majority&appName=Cluster0&ssl=true' >> .env
          echo MSG_QUEUE_URL='amqps://hrldvlgd:Qubq-0oyS2rAu-S0EYHHgyiDHzewkctl@puffin.rmq2.cloudamqp.com/hrldvlgd' >> .env
          echo EXCHANGE_NAME=ONLINE_STORE >> .env
          echo PORT=8001 >> .env
          cat .env

      - name: Create Products Env file
        working-directory: ./products
        run: |
          touch .env
          echo APP_SECRET='MySecretKey' >> .env
          echo MONGODB_URI='mongodb+srv://hiranya:hiranya@cluster0.dn0whwc.mongodb.net/products?retryWrites=true&w=majority&appName=Cluster0&ssl=true' >> .env
          echo MSG_QUEUE_URL='amqps://hrldvlgd:Qubq-0oyS2rAu-S0EYHHgyiDHzewkctl@puffin.rmq2.cloudamqp.com/hrldvlgd' >> .env
          echo EXCHANGE_NAME=ONLINE_STORE >> .env
          echo PORT=8002 >> .env
          cat .env
          
      - name: Generate deployment package
        run: |
          zip -r deploy.zip . -x '*.git'
      
      # - name: Deploy on Elastic beanstalk QA Env
      #   uses: einaregilsson/beanstalk-deploy@v20
      #   with:
      #     aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     application_name: youtube-ms
      #     environment_name: Youtubems-env
      #     version_label: "ver-${{ github.sha }}"
      #     region: eu-central-1
      #     deployment_package: deploy.zip

