name: Run SonarQube with Node.js

on:
  push:
    branches:
      - master

jobs:
  sonarcloud_ver:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install SonarQube Scanner for Node.js
      run: npm install -g sonarqube-scanner

    - name: Build and Run SonarQube analysis
      run: |
        sonar-scanner \
          -Dsonar.projectKey=cste-assignment \
          -Dsonar.organization=cste-assignment \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=$SONAR_TOKEN
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
